pypi-jax: Autospec creation for update from version 0.4.13 to version 0.4.14
Alexander Kolesnikov (1):
      Improve error message and the relevant test.

Alexey Radul (27):
      Test and implement ragged outputs of dot_general.
      Test and implement transposition of ragged arrays.
      Test and implement ragged einsum.
      Propagate more definitely_equal checks to fix more cases of broadcast_to.
      Type annotations.
      Better error message when broadcasting ragged to static shape.
      Test and implement ragged slicing.
      Force RaggedAxis axes to be sorted at rest, so that == is more reliable.
      Test a different configuration of einsum.
      More type annotations, and make transpose_ragged_axes a top-level function instead of a method.
      Abstract out and reuse the gather_shape_computation to predict which axes will end up ragged.
      Clearer test names.
      Test and implement slicing not dropping raggedness information.
      Revive indirection of RaggedAxis batch dims.
      Understanding batch_jaxpr better.
      Finish supporing bints and DArrays where the pile tests touch them.
      Physical HLO sharding for bint is the same as for the base type.
      Satisfy mypy with better type annotations.
      Force bint-typed arrays to int32 types underneath.
      Explicitly check for DShapedArray in _to_logical_sharding instead of returning a sharding by default.
      Fix type errors caught by pytype.
      Right.  Turns out jax2tf uses symbolic (as opposed to ragged) dynamic shapes, which do implement divmod for sharding.
      Fix typo.
      Test a few examples with jitting enabled and disabled.
      Record the example transformer layer as a test case.
      Rename Piles to Jumbles, to avoid unfortunate Imperial entanglements.
      Fix silly type error involving `dims_out` sometimes being a thunk and sometimes not.

Artem Belevich (2):
      Disable tests that trigger a known bug in cublasDtrsmBatched in cuda-12 on sm_60.
      Disable tests triggering a known bug in cuda-12.

Ayaka (2):
      Fix typo in documentation
      Fix typo: `ConcretizationError` -> `ConcretizationTypeError`

Chris Jones (4):
      [jax_triton] Expose Triton custom call callback in header file.
      Add `get_serialized_metadata` function to retrieve metadata from op's opaque data.
      [jax_triton] Split C++ only parts of Triton custom callback from Python parts.
      [jax_triton] Simplify auto-tuning code.

George Necula (34):
      [shape_poly] linalg.lu: for shape polymorphism for native serialization on CPU.
      [shape_poly] Cleanup the evaluation of dynamic shapes
      [jax2tf] Improve custom call safety check to detect mhlo.custom_call
      [shape_poly] Refactor some older support for shape polymorphism for linalg.
      [shape_poly] Refactor support for dynamic shapes for linalg.eig and linalg.eigh
      [shape_poly] linalg.triangular_solve: shape polymorphism with native lowering on CPU
      [shape_poly] linalg.schur: shape polymorphism with native lowering on CPU
      [shape_poly] Shape polymorphism support for approx_top_k
      Cleanup API usage related to shape polymorphism.
      Copybara import of the project:
      Add backwards compatibility test for Mosaic.
      [shape_poly] Cleanups for the shape polymorphism APIs.
      [shape_poly] Cleanup exported API symbols.
      Add support for shape assertions to RefinePolymorphicShapes
      [shape_poly] More cleanup for the internal APIs for shape polymorphism.
      Roll back #16689
      [shape_poly] More cleanup for the internal APIs for shape polymorphism.
      [jax2tf] Add backwards compatibility test for linalg.cholesky custom calls on CPU
      [jax2tf] Add backwards compatibility tests for linalg.svd on CPU
      [jax2tf] Add backward compatibility tests for linalg.eig on CPU.
      Separates ValidateStaticShapes from RefineDynamicShapes.
      Copybara import of the project:
      [jax2tf] Re-enable some tests for native serialization
      [jax2tf] Remove unnecessary test
      [jax2tf] Add backwards compatibility test for lax.triangular_solve on CPU
      [jax2tf] Add backwards compatibility for lax.linalg.schur on CPU
      [shape_poly] Reimplement the shape constraint checking using shape assertions.
      [shape_poly] Add support for max0 for symbolic dimensions.
      [jax2tf] Document the JAX serialization version numbers.
      Introduce version 8 of XlaCallModule.
      [shape_poly] Improve error messages for shape assertions
      [jax2tf] Added error for attempting to use wrong jax_serialization_version
      [jax2tf] Add support for serialization version 8.
      [shape_poly] Fix handling of dot_general with different lhs_dtype and rhs_dtype

Jake VanderPlas (37):
      jnp.convolve: add support for preferred_element_type
      errors: create TracerBoolConversionError for more targeted debugging tips
      [sparse] support custom JVP in sparsify
      Custom PRNG: improve test coverage when enable_custom_prng=false
      Drop support for numpy 1.21
      Add jax.scipy.stats.binom
      Fix integer overflow in gather batching rule
      jax.interpreters.pxla: remove deprecated functions:
      schur: fix broken jvp rule
      Require index update optional arguments to be passed by keyword.
      DOC: improve documentation for lax slicing routines
      Require ml_dtypes>=0.2
      NumpySignaturesTest: account for 'mean' param to std/var
      Fix scatter batching rule for scatter_apply
      Remove several deprecated jax.Array methods:
      remove deprecation warning test in preparation for removing deprecated APIs
      Remove several deprecated APIs
      pre-commit: update mypy to most recent version
      Remove obsolete jaxlib version checks
      Make jit work with custom float inputs
      type promotion: improve implicit type promotion error for float8 & int4
      make scatter-apply jvp notimplemented (for now...)
      remove stray print statement
      [sparse] support preferred_element_type in dot_general
      mypy: suppress annotation-unchecked notes
      support np.array(x) where x is a custom pytree with __jax_array__
      Re-parameterize jax.random.gamma for better behavior at endpoints
      make jvp(asarray, (1.,), (2.,)) produce Arrays
      Use standard framework for jax.tree* deprecation.
      Refactor opaque dtype implementation.
      Lower jax.numpy.dot to mixed-precision dot_general
      custom prng: introduce mechanism to identify key arrays by dtype
      CI: update jupytext to v0.14.7
      replace use of has_opaque_dtype
      fix deprecations in core.py
      lax.dynamic_slice: avoid negative index correction for unsigned indices
      Add implementation of jnp.put

Jake Vanderplas (1):
      Copybara import of the project:

Jannis Bolik (1):
      Update incorrect Dirichlet PDF in documentation

Jieying Luo (1):
      [PJRT C API] Add related C type definitions for key value get/put callback, as well as conversion between C and cpp types.

John QiangZhang (1):
      Improve the default value of `output_shape_dtype`.

Juliana Franco (1):
      Makes it possible to lower primitives with user-defined lowering rules.

Junwhan Ahn (1):
      Change `mhlo.is_same_data_across_replicas` from unit attr to bool attr

Lena Martens (1):
      Add back tracebacks to checkify's Error without leaking tracers.

Lukas Geiger (2):
      Remove obsolete numpy version checks
      Remove unneeded Python 3.9+ version checks

Marcus Chiam (1):
      Flax is changing the `RNNCellBase` API:

Matthew Johnson (3):
      Indirectify ragged axes across jitting boundaries, input- and output-side.
      einsum: inf inputs could cause superfluous nan outputs
      make _dot_general_batch_rule handle python builtin numeric types

Parker Schuh (4):
      Make the default driver in serialization be a global constant.
      `jax.lax.collapse` now takes Nones for stop_dimension.
      Change visibility for jax_export to public.
      Add support for int fields to compiler_options.

Patrick Kidger (2):
      Fix docstring for `jax.debug.{print,callback}`
      Add type annotation to `jnp.tensordot`

Peter Hawkins (24):
      Remove references to Python 3.8.
      Relax test tolerances.
      Update README to mention Windows support.
      Use lower-case PEP 585 names for types.
      Remove the old JAX/IREE integration.
      Remove --distinct_host_configuration from Bazel flags.
      Note that the MSVC studio 2019 redistributable is required for JAX on Windows.
      Avoid duplicate symbol definition.
      Disable tests that are flaky in CI.
      Import py_binary() rule from @rules_python.
      Fix warning about direct invocation of setup.py during jaxlib build.
      Fix broken jaxlib wheel build by moving LICENSE.txt to the correct location.
      Use the upstream MLIR strip-debuginfo pass instead of hand-rolling our own.
      Remove jax_jit_pjit_api_merge.
      Remove the jax_array config option, which does nothing.
      [JAX] Add support for multiple pytree registries.
      [JAX] Use MLIR argument locations instead of a bespoke jax.arg_info attribute.
      Delete pxla.make_sharded_device_array.
      Move _array_shard_arg helpers from pxla into array.
      Apply pyupgrade --py39-plus.
      Check `build` and `wheel` are installed before building `jaxlib`.
      Update XLA version to fix build failure.
      Update flags to use the ABSL typed flag API.
      Work around pytype error.

Rahul Batra (3):
      [ROCm]: Update README.md
      [ROCm]: Re-enable SvdOnTinyElement test
      [ROCm]: Re-enable EighIdentity test

Roy Frostig (19):
      outline jitted threefry `split` and `fold_in` subroutines
      resolve conditionals to default "shared operand form" more often
      add corner-case `cond` resolution fix to changelog
      add `impl` option to random key constructors that picks the RNG implementation
      increase random test coverage over RNG key constructors and representations
      avoid raw key arrays in typed key sharding test
      broaden `random.fold_in` annotation to allow for int arrays
      test non-threefry RNGs across both typed and raw key formats
      match behavior of double-threefry test RNG and standard threefry RNG
      move and remove code in `random_test`
      parameterize two random tests over key constructors
      consistently seed keys indirectly by test class method in `LaxRandomTest`
      rename `seed_prng` test method to `make_key`
      AOT doc: fix `lower`/`compile` expression in error example
      AOT: better error messages on call signature mismatch
      accept general `shape` option in `jax.random.split`
      document and test `CustomVJPPrimal` type as API symbol
      API compatibility policy: expand on numerics and randomness
      add `jax.prng` to uncovered modules list in API policy

Sergei Lebedev (1):
      Removed the type annotation of `orig_out_sharding_handlers`

Sharad Vikram (3):
      Add discharge rules for scan/while
      Add Mosaic to Jaxlib and expose bindings in `jax.experimental.mosaic`
      Enable building jaxlib w/ Mosaic

Skye Wanderman-Milne (6):
      Update version numbers and changelog post 0.4.13 release
      Cloud TPU CI: make sure we update test deps and upgrade protobuf version
      Make //jax:tpu_custom_call respect --//jax:build_jaxlib=false
      Move _tpu_ext.cc to jaxlib/mlir/_mlir_libs and set RPATH correctly
      Update WORKSPACE and setup.py in preparation for jax/jaxlib 0.4.14 release
      Slightly downgrade xla version to avoid PJRT C API incompat

TJ (1):
      Change default memory allocation to 75% instead of 90%

Tao Wang (3):
      Add get_profiled_instructions_proto API in jax.experimental.profiler to get profiled instructions proto.
      Enable to set fdo_profile through XLA python client.
      Enable passing fdo_profile in compiler_options in pxla.py

Yash Katariya (12):
      [Rollback] Remove py3.8 support from jax as per https://jax.readthedocs.io/en/latest/deprecation.html
      Copybara import of the project:
      Raise an error if a user passes None to `host_local_array_to_global_array` or `global_array_to_host_local_array`
      Make `sharding` on ShapeDtypeStruct a property that always exists. The previous behavior was it only existed if sharding was not None.
      Add donate_argnames to jax.jit. This works similarly to static_argnames.
      jax.jit now works correctly if both donate_argnums and donate_argnames are specified.
      Delete in_axis_resources and out_axis_resources from pjit since it's been more than 3 months since their deprecation. The replace is to use in_shardings and out_shardings. You can still pass PartitionSpecs to {in|out}_shardings to pjit.
      Make _parsed_pspec a kw_only argument. This should be backwards compatible since you pass an arg as a kwarg too.
      Add memory_kind to NamedSharding, SingleDeviceSharding, PositionalSharding and GSPMDSharding.
      Skip PgleTest.testPassingFDOProfile if xla_extension_version < 169
      Error if memory_kind is not correct for the devices in Shardings during initialization.
      Make _remake internal and add return type hints

jax authors (9):
      Allow other backends to run the `array_test.py` test.
      Improve error message to point the way to Megacore.
      Remove deprecated `compiler_ir` from `Compiled`
      Add function names to stack frames.
      Add deprecation of `jax.stages.Compiled.compiler_ir` to the change log
      Include compile time along with executable in cache entry.
      Tweaks the utility function `_get_ppspec_from_executable` to get the shardings directly from the executable (instead of from its HLO modules).
      Integrate LLVM at llvm/llvm-project@571c1292b693
      Previously, using sparse.todense on a BCSR matrix with sparse.sparsify would raise `NotImplementedError: sparse rule for todense is not implemented`. By adding the sparse rule, it will resolve this issue.

lenamartens (1):
      Checkify: remove duplicate line.

treyra (2):
      Fixed _mapped_axis_size raising an uncaught TypeError
      Added test for vmap inconsistent sized arrays msg